version: 2.1

jobs:
  bump_version:
    docker:
      - image: tuplestream/bumpversion:latest
    steps:
      - add_ssh_keys:
          fingerprints:
            - "35:56:55:9d:b0:4e:f1:bb:72:04:9d:73:cd:6c:dd:69"
      - checkout
      - run:
          name: run bumpversion and push
          command: bump
  build_images:
    docker:
      - image: docker:18.06.3-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build base image
          command: ./build.sh base-build
      - run:
          name: build integration test env
          command: ./build.sh integrationtest
      - run:
          name: build bumpversion
          command: ./build.sh bumpversion
      - run:
          name: build swift build env
          command: ./build.sh swift-env
      - run:
          name: build golang build env
          command: ./build.sh golang
      - run:
          name: build aws-cli
          command: ./build.sh aws-cli
      - run:
          name: build-shellcheck
          command: ./build.sh shellcheck

workflows:
  version: 2
  build_and_test:
    jobs:
      - bump_version:
          filters:
            branches:
              only:
                - master
      - build_images:
          requires:
            - bump_version
