version: 2.1

jobs:
  build:
    docker:
      - image: docker:18.06.3-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build-base image
          command: |
            cd build-base
            docker build . -t tuplestream/build-base

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
