version: 2.1

jobs:
  build_base:
    docker:
      - image: docker:18.06.3-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build base image
          command: |
            export VERSION=$(cat VERSION)
            cd base-build
            docker build . -t tuplestream/base-build:$VERSION
            echo $DKPW | docker login --username m0wfo --password-stdin
            docker push tuplestream/base-build:$VERSION
            docker tag tuplestream/base-build:$VERSION tuplestream/base-build:latest
            docker push tuplestream/base-build:latest
      - run:
          name: build bumpversion
          command: |
            export VERSION=$(cat VERSION)
            cd bumpversion
            docker build . -t tuplestream/bumpversion:$VERSION
            echo $DKPW | docker login --username m0wfo --password-stdin
            docker push tuplestream/bumpversion:$VERSION
            docker tag tuplestream/bumpversion:$VERSION tuplestream/bumpversion:latest
            docker push tuplestream/bumpversion:latest
workflows:
  version: 2
  build_and_test:
    jobs:
      - bump_version:
          filters:
            branches:
              only:
                - master
      - build_base:
          requires:
            - bump_version
