version: 2.1

jobs:
  bump_version:
    docker:
      - image: tuplestream/bumpversion:latest
    steps:
      - add_ssh_keys:
          fingerprints:
            - "35:56:55:9d:b0:4e:f1:bb:72:04:9d:73:cd:6c:dd:69"
      - checkout
      - run:
          name: run bumpversion and push
          command: bump
  build_images:
    docker:
      - image: docker:18.06.3-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build base image
          command: |
            export VERSION=$(cat VERSION)
            cd base-build
            docker build . -t tuplestream/base-build:$VERSION
            echo $DKPW | docker login --username m0wfo --password-stdin
            docker push tuplestream/base-build:$VERSION
            docker tag tuplestream/base-build:$VERSION tuplestream/base-build:latest
            docker push tuplestream/base-build:latest
      - run:
          name: build bumpversion
          command: |
            export VERSION=$(cat VERSION)
            cd bumpversion
            docker build . -t tuplestream/bumpversion:$VERSION
            echo $DKPW | docker login --username m0wfo --password-stdin
            docker push tuplestream/bumpversion:$VERSION
            docker tag tuplestream/bumpversion:$VERSION tuplestream/bumpversion:latest
            docker push tuplestream/bumpversion:latest
      - run:
          name: build swift build env
          command: |
            export VERSION=$(cat VERSION)
            cd swift-env
            docker build . -t tuplestream/swift-env:$VERSION
            echo $DKPW | docker login --username m0wfo --password-stdin
            docker push tuplestream/swift-env:$VERSION
            docker tag tuplestream/swift-env:$VERSION tuplestream/swift-env:latest
            docker push tuplestream/swift-env:latest
      - run:
          name: build golang build env
          command: |
            export VERSION=$(cat VERSION)
            cd golang
            docker build . -t tuplestream/golang:$VERSION
            echo $DKPW | docker login --username m0wfo --password-stdin
            docker push tuplestream/golang:$VERSION
            docker tag tuplestream/golang:$VERSION tuplestream/golang:latest
            docker push tuplestream/golang:latest

workflows:
  version: 2
  build_and_test:
    jobs:
      - bump_version:
          filters:
            branches:
              only:
                - master
      - build_images:
          requires:
            - bump_version
